### ISSUE TITLE
Encrypt NWC connection string with password

### ISSUE THREAD

**Issue by bumi** [getAlby/pos#2]
Let users enter an unlock password

**Comment by rolznz** [comment]
@bumi what is the benefit / usecase here?

**Comment by bumi** [comment]
The get parameters can be logged everywhere if you for example add the decryption password as anchor then it stays in the browser and is not send to the servers.

**Comment by reneaaron** [comment]
The connection string only allows you to create invoices, not do anything else. 

I don't think this is a real problem here as a potential attacker has nothing to gain.
