### ISSUE TITLE
Fiat support to enter amounts in different currencies

### ISSUE THREAD

**Issue by bumi** [getAlby/pos#4]
- Allow users to choose a fiat currency
 - Allow users to charge in fiat (enter e.g. 1 USD)

**Comment by Toheeb-Ojuolape** [comment]
Hi @bumi @rolznz I currently have a PR that addresses this issue. Please kindly check it out. I look forward to your feedback 🙇🏾

https://github.com/getAlby/pos/pull/28

**Comment by rolznz** [comment]
Implemented in https://github.com/getAlby/pos/pull/29
